version: '3.1'

services:
  db:
    container_name: mysql
    image: mysql:8.4
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testdb
    # (this is just an example, not intended to be a production configuration)
    volumes:
      - $PWD/init.sql:/docker-entrypoint-initdb.d/init.sql

